init:
  - git config --global core.autocrlf true
install:
  - ps: scripts\envsetup.ps1
version: 0.1.{build}
clone_depth: 1
nuget:
  disable_publish_on_pr: true
build:
  verbosity: normal
assembly_info:
  patch: true
  file: **\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-alpha1'
configuration:
  - Debug
  - Release
artifacts:
- path: 'artifacts\bin\**\Release\*.nupkg'
  name: myget
deploy:
- provider: NuGet
  server: https://www.myget.org/feed/Packages/chriskxu
  api_key:
    secure: 2eXAuI3EbjRxVMoS/hLPu2W6gRROBj5UaSQkmcU/tUel8Gt1TuHtRMdTWSeeK3Wj
  skip_symbols: true
test: off
