init:
  - git config --global core.autocrlf true
install:
  - ps: scripts\envsetup.ps1
version: 0.1.{build}
clone_depth: 1
nuget:
  disable_publish_on_pr: true
build:
  verbosity: normal
artifacts:
- path: '*.nupkg'
  name: myget
deploy:
- provider: NuGet
  server: https://www.myget.org/feed/Packages/chriskxu
  api_key:
    secure: 2eXAuI3EbjRxVMoS/hLPu2W6gRROBj5UaSQkmcU/tUel8Gt1TuHtRMdTWSeeK3Wj
  artifact: myget
test: off
