init:
  - git config --global core.autocrlf true
os: Visual Studio 2015
build_script:
  - ps: scripts\build.ps1
version: 0.1.{build}
cache:
  - '%UserProfile%\.dnx'
clone_depth: 1
nuget:
  disable_publish_on_pr: true
environment:
  DNX_BUILD_VERSION: $(APPVEYOR_BUILD_NUMBER)
configuration:
  - Release
artifacts:
- path: 'artifacts\Release\*.nupkg'
  name: myget
deploy:
- provider: NuGet
  server: https://www.myget.org/F/chriskxu/api/v2/package
  api_key:
    secure: 2eXAuI3EbjRxVMoS/hLPu2W6gRROBj5UaSQkmcU/tUel8Gt1TuHtRMdTWSeeK3Wj
  skip_symbols: true
  artifact: /.*\.nupkg/
test: off
